
const DB_NAME='pledge-explorer-db', STORE='datasets', KEY='current';
let rows=[], meta={};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const field=(...names)=>Object.keys(rows[0]||{}).find(k=>names.some(n=>k.toLowerCase().trim()===n.toLowerCase()));
const uniq=a=>[...new Set(a.filter(v=>v!==null&&v!==undefined&&String(v).trim()!=="").map(v=>String(v).trim()))];
function db(){return new Promise((res,rej)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>q.result.createObjectStore(STORE);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function put(v){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(v,KEY);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function get(){const d=await db();return new Promise((res,rej)=>{const q=d.transaction(STORE).objectStore(STORE).get(KEY);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function del(){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).delete(KEY);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function parseFile(file){const reader=new FileReader();reader.onload=async e=>{try{const wb=XLSX.read(e.target.result,{type:'array'});const sheet=wb.Sheets['Pledge Coding']||wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(sheet,{defval:''});meta={name:file.name,loaded:new Date().toISOString(),sheet:wb.SheetNames.includes('Pledge Coding')?'Pledge Coding':wb.SheetNames[0]};await put({rows,meta});boot()}catch(err){alert('Could not read workbook: '+err.message)}};reader.readAsArrayBuffer(file)}
function boot(){if(!rows.length)return;$('#emptyState').classList.add('hidden');$('#app').classList.remove('hidden');renderAll()}
function testable(){const s=field('Survives Step 2?','Survives Step 2');return s?rows.filter(r=>String(r[s]).trim().toUpperCase()==='Y'):rows}
function renderAll(){const data=testable(), p=field('Presidency'), f=field('Fulfillment','Fulfilment'), t=field('Pledge Type');const pres=uniq(data.map(r=>r[p]));
 $('#statPres').textContent=pres.length;$('#centerCount').textContent=pres.length;$('#statPledges').textContent=data.length.toLocaleString();$('#centerPledges').textContent=data.length.toLocaleString()+' pledges';
 const fv=data.map(r=>String(r[f]||'').toLowerCase()); const countWord=w=>fv.filter(x=>x.includes(w)).length;
 $('#statFull').textContent=countWord('full').toLocaleString();$('#statPartial').textContent=countWord('partial').toLocaleString();$('#statNot').textContent=countWord('not').toLocaleString();
 renderWheel(data,p,pres,f);renderBars(data,p,pres,f);fillFilters(data,p,f,t);renderTable();renderAnalysis(data,f,t);$('#dataInfo').textContent=`${meta.name||'Workbook'} · ${rows.length.toLocaleString()} coded rows · loaded ${meta.loaded?new Date(meta.loaded).toLocaleString():''}`;
}
function renderWheel(data,p,pres,f){const w=$('#wheel');w.innerHTML='';const palette=['#d8e2e9','#eadfba','#dfc7a4','#cddbd3'];pres.forEach((name,i)=>{const a=360/pres.length*i-90,d=document.createElement('div');d.className='segment';d.style.transform=`rotate(${a}deg)`;d.innerHTML=`<div class="segment-inner" style="--seg:${palette[i%palette.length]}"><span style="transform:rotate(${-a}deg)">${name}</span></div>`;const subset=data.filter(r=>String(r[p]).trim()===name);d.onmouseenter=e=>{const tip=$('#tooltip');tip.innerHTML=`<b>${name}</b><br>${subset.length} testable pledges`;tip.classList.remove('hidden')};d.onmousemove=e=>{const tip=$('#tooltip');tip.style.left=e.clientX+14+'px';tip.style.top=e.clientY+14+'px'};d.onmouseleave=()=>$('#tooltip').classList.add('hidden');d.onclick=()=>{$('.nav[data-view="pledges"]').click();$('#presFilter').value=name;renderTable()};w.appendChild(d)})}
function renderBars(data,p,pres,f){const box=$('#barChart');box.innerHTML='';pres.forEach(name=>{const sub=data.filter(r=>String(r[p]).trim()===name), known=sub.filter(r=>String(r[f]||'').trim()), full=known.filter(r=>String(r[f]).toLowerCase().includes('full')).length, pct=known.length?Math.round(full/known.length*100):0;box.insertAdjacentHTML('beforeend',`<div class="bar-row"><b>${name}</b><div class="bar-track"><div class="bar-fill" style="width:${pct}%"></div></div><span>${pct}%</span></div>`)})}
function fillSelect(el,vals){const first=el.options[0].outerHTML;el.innerHTML=first+vals.map(v=>`<option>${String(v).replaceAll('&','&amp;').replaceAll('<','&lt;')}</option>`).join('')}
function fillFilters(data,p,f,t){fillSelect($('#presFilter'),uniq(data.map(r=>r[p])));fillSelect($('#fulFilter'),uniq(data.map(r=>r[f])));fillSelect($('#typeFilter'),uniq(data.map(r=>r[t])))}
function renderTable(){const data=testable(),p=field('Presidency'),f=field('Fulfillment','Fulfilment'),t=field('Pledge Type'),s=field('Statement'),sec=field('Section'),notes=field('Notes');let filtered=data.filter(r=>(!$('#presFilter').value||String(r[p])===$('#presFilter').value)&&(!$('#fulFilter').value||String(r[f])===$('#fulFilter').value)&&(!$('#typeFilter').value||String(r[t])===$('#typeFilter').value));const q=$('#searchBox').value.toLowerCase();if(q)filtered=filtered.filter(r=>[r[s],r[sec],r[notes]].join(' ').toLowerCase().includes(q));const cols=[p,sec,s,t,f].filter(Boolean);$('#tableHead').innerHTML='<tr>'+cols.map(c=>`<th>${c}</th>`).join('')+'</tr>';$('#tableBody').innerHTML=filtered.slice(0,500).map(r=>'<tr>'+cols.map(c=>`<td class="${c===s?'statement':''}">${String(r[c]??'').replaceAll('&','&amp;').replaceAll('<','&lt;')}</td>`).join('')+'</tr>').join('');$('#tableCount').textContent=`Showing ${Math.min(filtered.length,500).toLocaleString()} of ${filtered.length.toLocaleString()} matching pledges${filtered.length>500?' (first 500 shown)':''}.`}
function renderAnalysis(data,f,t){const vals=uniq(data.map(r=>r[f])), counts=vals.map(v=>data.filter(r=>String(r[f])===v).length), total=counts.reduce((a,b)=>a+b,0)||1;let cur=0,parts=counts.map((c,i)=>{const st=cur,en=cur+c/total*360;cur=en;return `hsl(${210+i*55} 25% ${55+i*7}%) ${st}deg ${en}deg`});$('#donut').innerHTML=`<div><div class="donut" style="background:conic-gradient(${parts.join(',')})"></div><p>${vals.map((v,i)=>`${v}: <b>${counts[i]}</b>`).join(' · ')}</p></div>`;const types=uniq(data.map(r=>r[t])).map(v=>[v,data.filter(r=>String(r[t])===v).length]).sort((a,b)=>b[1]-a[1]);const max=Math.max(...types.map(x=>x[1]),1);$('#typeBars').innerHTML=types.map(([v,c])=>`<div class="bar-row"><b>${v}</b><div class="bar-track"><div class="bar-fill" style="width:${c/max*100}%"></div></div><span>${c}</span></div>`).join('')}
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.add('hidden'));$('#view-'+b.dataset.view).classList.remove('hidden')});
['fileInput','fileInput2'].forEach(id=>$('#'+id).onchange=e=>e.target.files[0]&&parseFile(e.target.files[0]));
$('#replaceData').onclick=()=>$('#fileInput2').click();$('#deleteData').onclick=async()=>{if(confirm('Delete the locally stored dataset from this browser?')){await del();location.reload()}};
['searchBox','presFilter','fulFilter','typeFilter'].forEach(id=>$('#'+id).addEventListener(id==='searchBox'?'input':'change',renderTable));
(async()=>{const saved=await get();if(saved){rows=saved.rows||[];meta=saved.meta||{};boot()}})();
